/* Portable, edition-scoped course content for Contemporary Horeca Scene. Replace this seed with a CMS/API adapter without changing the views. */
window.COURSE = {
  id: 'contemporary-horeca-scene', title: 'Contemporary Horeca Scene', edition: 2026,
  descriptor: 'A living digital elective that reads the contemporary horeca scene through rankings, design, neurogastronomy, technology and entrepreneurship — then asks you to build a venue of your own, down to a physical mockup.',
  institution: 'Hotel Institute Montreux', author: 'Egor Tarasenko',
  access: 'Password-protected edition. Access is granted per cohort.',
  modules: [
    {id:'future', number:'01', title:'Hospitality Futures', description:'Read the signals reshaping hospitality, from new guest expectations to the cultural power of a great venue.', image:'horeca-concept-pitch.jpg', lessons:[
      {id:'signals', title:'Reading the signals', duration:'12 min', intro:'Hospitality is not standing still. The most useful question is not what is trending, but what a trend reveals about the way people want to spend their time.', body:'A shift in guest behaviour rarely arrives as a single invention. It appears first in small choices: where people gather, what they are willing to wait for, and what they tell friends afterwards. Operators who notice these signals early can make more considered decisions about concept, service and investment.', ideas:['A trend is a signal to investigate, not a brief to copy.','Experience is designed across the entire guest journey.','Strong concepts make deliberate choices about what they will not be.'], case:'Bar Leone, Hong Kong', challenge:'Choose one change in guest behaviour you have noticed. What opportunity could it create for a hospitality concept?'}]},
    {id:'experience', number:'02', title:'Experience Design', description:'Explore how space, service, sound, light and interaction shape the moments guests remember.', image:'horeca-interior-design.jpg', lessons:[
      {id:'atmosphere',title:'Designing atmosphere',duration:'14 min',intro:'Atmosphere is not decoration. It is the cumulative effect of hundreds of choices, made legible to a guest through a single evening.',body:'Light changes the pace of a room. Sound affects conversation. Tableware changes how a dish feels in the hand. The most compelling spaces bring these elements into alignment with the promise of the concept. Think of a bar or a restaurant as a sweet fairy tale: for two hours the guest agrees to believe in a world you have built, where the light is warm, the noise of the street disappears and everything on the table belongs to the story. The spell is fragile. One wrong detail — a harsh overhead light, a plastic tray, a dirty door handle, a ringtone from the service station, a printer where the guest can see it — wakes the guest up instantly, and the rest of the evening is spent in a room rather than in a dream. Atmosphere design is therefore a discipline of continuity: everything the guest can see, hear, touch and smell must stay inside the same story.',ideas:['Design for a sequence of moments, not a static photograph.','A venue is a sweet fairy tale: any small detail can instantly wake the guest from the dream.','Service choreography is part of spatial design — back-of-house must never leak into the story.','A sensory detail should reinforce the concept, not distract from it.'],case:'Himkok, Oslo',challenge:'Map three scenes in a venue you know: arrival, the peak moment and farewell. Identify one design choice in each — and one detail that breaks the spell.'}]},
    {id:'neuro', number:'03', title:'Neurogastronomy', description:'Understand how perception, psychology and environment influence food and beverage experiences.', image:'horeca-neurogastronomy-serve.jpg', lessons:[
      {id:'perception',title:'The senses at the table',duration:'16 min',intro:'Flavour is experienced through more than taste. Context, expectation and the other senses all participate in what a guest perceives.',body:'Gastrophysics examines how physical and psychological factors shape eating and drinking. A useful hospitality application is to treat the setting as part of the offer: the soundscape, vessel, lighting and story may all influence how an experience is interpreted.',ideas:['Perception is constructed from multiple sensory cues.','The remembered peak and ending can shape an entire visit.','Sensory design should be tested, not assumed.'],case:'A multisensory World Class serve',challenge:'Propose one sensory detail that could make a signature dish more memorable. Explain the intended effect.'}]},
    {id:'concepts', number:'04', title:'Restaurant & Bar Concepts', description:'Build a clear point of view through positioning, storytelling, atmosphere and business logic.', image:'horeca-craft-bar.jpg', lessons:[
      {id:'point-of-view',title:'A concept with a point of view',duration:'13 min',intro:'A concept becomes useful when it helps a team make choices. It should be more than a moodboard or a list of references.',body:'A compelling venue connects audience, occasion, offer, space and economics. Benchmarks can sharpen a point of view, but the work is deciding what to translate and what to leave behind.',ideas:['Define the guest and the occasion before the aesthetic.','A proposition should be clear enough to guide operations.','Distinctiveness and commercial logic can reinforce one another.'],case:'Bar Leone, Hong Kong',challenge:'Write a one-sentence proposition for a new venue, including audience, occasion and what makes it different.'}]},
    {id:'technology', number:'05', title:'Technology & Automation', description:'Consider where technology can improve operations and where the human touch matters most.', image:'horeca-tech-operations.jpg', lessons:[
      {id:'automation',title:'Automation without losing humanity',duration:'15 min',intro:'Technology should not simply make hospitality faster. It should make it better.',body:'The right tools reduce friction for guests and teams. Reservation systems, forecasting, inventory tools and kitchen displays can support consistency, but they do not replace judgement, generosity or a well-timed human response.',ideas:['Automate repetition; protect moments where human attention creates value.','Evaluate technology across guest experience and team experience.','A useful implementation begins with a clearly defined problem.','Hide the machinery: technology that guests can see working is scenery that broke.'],case:'Technology in contemporary F&B operations',challenge:'Choose one repetitive task to automate in a venue. What will the team do with the time this creates?'}]},
    {id:'ai', number:'06', title:'AI in Hospitality', description:'Assess emerging AI workflows, their opportunities, limitations and human implications.', image:'horeca-ai-mixology-lab.jpg', lessons:[
      {id:'human-ai',title:'AI as a creative and operational tool',duration:'17 min',intro:'AI can help teams generate options and work with information. It cannot own the responsibility for what a hospitality business promises.',body:'From creative briefs to demand planning, AI tools can expand a team’s capacity. Their value depends on good inputs, critical review and thoughtful decisions about privacy, bias and work. Hospitality remains a human promise, even when some of its systems are automated.',ideas:['Use AI to widen exploration, then apply human judgement.','Be transparent about consequential automated decisions.','Do not mistake fluent output for reliable evidence.'],case:'An AI-assisted beverage brief',challenge:'Describe one hospitality workflow where AI could help, one risk to manage and the human decision that must remain.'}]},
    {id:'fnb', number:'07', title:'Food & Beverage Futures', description:'Look at new formats, ingredients, beverage culture and changing consumer behaviour.', image:'horeca-sustainable-terroir.jpg', lessons:[
      {id:'new-formats',title:'The next table',duration:'12 min',intro:'The future of food and beverage is shaped by culture, access and changing definitions of value.',body:'New formats emerge as operators respond to local identity, resource constraints and new occasions. A strong offer is rooted in a point of view about place and people, rather than novelty alone.',ideas:['Local context can be a source of distinction.','Value is shaped by relevance as much as price.','New formats need viable operating models.'],case:'Tuju, São Paulo',challenge:'Identify a food or beverage behaviour gaining momentum in your market. How might a venue respond with integrity?'}]},
    {id:'entrepreneurship', number:'08', title:'Entrepreneurship', description:'Move from a strong idea to an operationally grounded hospitality business.', image:'horeca-concept-pitch.jpg', lessons:[
      {id:'from-idea',title:'From idea to operating model',duration:'18 min',intro:'A hospitality business is a promise, delivered repeatedly by a team within real constraints.',body:'Concept development balances desirability, feasibility and viability. Define the guest and value proposition, then test the operating assumptions behind the experience: capacity, staffing, supply, pricing and the rhythm of demand.',ideas:['A clear proposition makes operating trade-offs visible.','Small tests can reduce uncertainty before major investment.','Culture and economics are both part of the concept.'],case:'From pop-up to permanent concept',challenge:'Name the riskiest assumption in your concept and design a low-cost way to test it.'}]},
    {id:'budget', number:'09', title:'Budget Realisation & Scenography', description:'Prove that a venue with soul does not need a large budget: found objects, theatrical decorative techniques — and a physical mockup of your own project built from paper, like stage scenery.', image:'horeca-atmosphere-candle.jpg', lessons:[
      {id:'budget-builds',title:'Soul before budget',duration:'16 min',intro:'A venue does not need a large budget to feel alive. It needs a point of view, and the patience to hunt for objects that carry one.',body:'Some of the most convincing rooms in the world were assembled rather than constructed: doors, mirrors and chairs from flea markets, marble offcuts, reclaimed timber, crates turned into shelving, an espresso machine bought second-hand, signage painted by hand, a chandelier found on a street corner. What makes these rooms work is not the low cost but the coherence — every object was chosen by the same pair of eyes and belongs to the same story. A budget limit is also a creative brief: when you cannot buy a look from a catalogue, you have to invent one, and the result is far harder for a competitor to copy. The working method is simple. Write down what the room must feel like, then go hunting for that feeling in flea markets, auctions, demolition yards, estate sales, restaurant liquidations and the street — before you open a single supplier catalogue. Joi Espresso Bar was built exactly this way: the author of this course assembled the whole space from the street and flea markets, without a large investment, and it holds together because the story came first and the objects were found to serve it. Money buys speed and finish. Intention buys soul.',ideas:['Write the feeling first, then go hunting for it: flea markets, auctions, demolition yards, liquidations, the street.','Mismatched objects read as curated when one point of view chose them.','A low budget is a creative brief, not a limitation — what you cannot buy, you must invent.','Repair, repurpose and re-upholster before replacing; patina is expensive to fake and free to keep.','Money buys speed and finish. Intention buys soul.'],case:'Joi Espresso Bar — assembled from the street and flea markets',challenge:'List ten elements of your concept. For each, note one way to source it second-hand, reuse it or build it yourself — and what it would cost.'},
      {id:'scenography',title:'Theatrical techniques & the paper mockup',duration:'19 min',intro:'Theatre has always known how to build a believable world cheaply, for one evening only. A venue is the same craft: scenery, light and props, arranged so that the guest believes.',body:'Scenography is the art of making a world convincing on a budget that would never survive a building permit: painted flats that read as marble or plaster, forced perspective that makes a small room deeper, a backdrop that turns a blank wall into a horizon, gauze and scrim that soften a corner, a single practical lamp that anchors an entire table. The decorative techniques come straight from the stage — trompe-l’œil, glazing and patina, distressing, stencil and gold leaf, faux bois and faux marbre, drapery and upholstery, haze and one tight beam of light. Used deliberately, they deliver the feeling of expensive materials for almost nothing. The rule is the same as everywhere else in this course: a theatrical trick must support the story and never announce itself, because the moment a guest notices the trick, the fairy tale ends. Then build the story with your hands. The final exercise of the course is a physical mockup of your own project — paper, cardboard, matchboxes, wire, fabric scraps, clay, printed photographs, a small torch for light. Not a floor plan: a set. Choose a scale you can hold (1:20 or 1:50), decide where the guest enters, what they see first, where the light comes from, which materials are real and which are painted illusions, and which three details carry the atmosphere. Photograph it at guest height. A mockup is the fastest way to discover that an idea which looked elegant in a document does not stand up in three dimensions — and the most persuasive object you can place in front of an investor, a landlord or a future team.',ideas:['Borrow from the stage: painted flats, forced perspective, backdrops, scrim, haze and a single tight beam.','Trompe-l’œil, glazing, patina, stencil, gold leaf and re-upholstery imitate expensive materials for almost nothing.','A theatrical trick must support the story, never announce itself.','Build the mockup as a set, not a plan: entrance, first sightline, light source, three atmosphere details.','Photograph the mockup at guest height — that is the image you will pitch with.'],case:'Stagecraft in venue design',challenge:'Build a physical mockup of your concept from paper, cardboard and found materials. Photograph it at guest height and name the three details that carry the atmosphere.'}]},
    {id:'final', number:'10', title:'Final Challenge', description:'Bring your thinking together. Design the hospitality concept of tomorrow — and hold it in your hands as a mockup.', image:'horeca-concept-pitch.jpg', lessons:[
      {id:'final-brief',title:'Design the hospitality concept of tomorrow',duration:'20 min',intro:'Imagine you are building a hospitality concept for 2030. Make a case for the experience, for the business that can deliver it — and for the set that makes guests believe.',body:'Your final concept should connect audience, experience, space, food and beverage, technology and a credible operating model, and it should be honest about how it will be realised: what is bought, what is found, what is built and what is painted. Submit the concept together with the physical mockup you built in Module 09 — paper, cardboard and light, like stage scenery — photographed at guest height. The strongest submissions demonstrate a clear point of view, explain how the details work together and show that the dream survives contact with a budget.',ideas:['Make the guest and the occasion specific.','Show how design, service and technology reinforce one another.','Communicate the business logic behind the experience.','Present the mockup: entrance, first sightline, light and the three details that carry the atmosphere.','Keep the fairy tale intact — name the details that could wake the guest up, and how you removed them.'],case:'Your own concept, benchmarked against the industry',challenge:'Present your concept, target audience, guest journey, food and beverage offer, technology choices, business model, sourcing and budget plan, visual direction — and the photographs of your physical mockup.'}]}
  ],
  cases:[
    {title:'Bar Leone',location:'Hong Kong',year:'2025',industry:'Bar culture · Guest experience',image:'horeca-craft-bar.jpg',context:'A contemporary neighbourhood bar framed around accessible, familiar drinks and a generous style of hospitality.',what:'Its proposition puts approachability and consistency at the centre of a globally visible bar concept.',why:'The case invites students to question whether innovation always needs to look complicated.',takeaway:'Clarity of intent can be more distinctive than visual or technical excess.'},
    {title:'Joi Espresso Bar',location:'Author’s own project',year:'Budget build',industry:'Espresso bar · Found objects & scenography',image:'horeca-atmosphere-candle.jpg',context:'A small espresso bar assembled by the author of this course almost entirely from what the street and the flea markets offered — furniture, fixtures, equipment and objects other people had already discarded.',what:'Instead of ordering a fitted interior, the space was built piece by piece: second-hand and reclaimed objects, adjusted, repaired and re-finished by hand until the room held together as one story. Theatrical decorative techniques did the rest of the work that a large budget would normally do.',why:'It is direct evidence that a venue with soul does not require a large investment. The constraint became the character: the room feels personal because every object was chosen deliberately rather than specified from a catalogue.',takeaway:'Budget is not the opposite of atmosphere. You do not always need enormous money to open something with soul — you need a point of view and the patience to hunt for it.'},
    {title:'Tuju',location:'São Paulo',year:'2026',industry:'Restaurant · Place & personalisation',image:'horeca-sustainable-terroir.jpg',context:'A restaurant concept that connects its menu to the rhythms of its environment and the character of its place.',what:'Seasonal themes and thoughtful guest details create a coherent narrative beyond the plate.',why:'It illustrates how local identity and considerate service can support an ambitious dining experience.',takeaway:'Personalisation is most meaningful when it grows from a real point of view.'},
    {title:'Himkok',location:'Oslo',year:'Case file',industry:'Bar · Design & circularity',image:'horeca-interior-sconces.jpg',context:'A bar whose approach brings together atmosphere, production and a distinctive sense of place.',what:'The case gives a lens on how spatial choices and in-house craft can reinforce a venue’s identity.',why:'Design is treated as an operating decision and part of the story, not a surface layer.',takeaway:'The best concepts make their values tangible in the way the venue works.'}
  ],
  updates:[
    {tag:'EDITION NOTE',title:'A living elective',date:'September 2026',text:'The 2026 edition is designed to evolve with hospitality — new cases and tools can be added without changing the learning journey.'},
    {tag:'NEW MODULE',title:'Budget Realisation & Scenography',date:'September 2026',text:'Module 09 joins the edition: building a venue with soul on a small budget, theatrical decorative techniques borrowed from the stage, and a final physical mockup of every student’s own project, made from paper and found materials like stage scenery.'}
  ]
};
