/* Portable, edition-scoped course content. Replace this seed with a CMS/API adapter without changing the views. */
window.COURSE = {
  id: 'future-of-hospitality', title: 'The Future of Hospitality', edition: 2026,
  descriptor: 'A digital elective exploring the ideas, technologies and experiences shaping the next generation of hospitality.',
  institution: 'Hotel Institute Montreux', author: 'Egor Tarasenko',
  modules: [
    {id:'future', number:'01', title:'The Future of Hospitality', description:'Read the signals reshaping hospitality, from new guest expectations to the cultural power of a great venue.', image:'horeca-concept-pitch.jpg', lessons:[
      {id:'signals', title:'Reading the signals', duration:'12 min', intro:'Hospitality is not standing still. The most useful question is not what is trending, but what a trend reveals about the way people want to spend their time.', body:'A shift in guest behaviour rarely arrives as a single invention. It appears first in small choices: where people gather, what they are willing to wait for, and what they tell friends afterwards. Operators who notice these signals early can make more considered decisions about concept, service and investment.', ideas:['A trend is a signal to investigate, not a brief to copy.','Experience is designed across the entire guest journey.','Strong concepts make deliberate choices about what they will not be.'], case:'Bar Leone, Hong Kong', challenge:'Choose one change in guest behaviour you have noticed. What opportunity could it create for a hospitality concept?'}]},
    {id:'experience', number:'02', title:'Experience Design', description:'Explore how space, service, sound, light and interaction shape the moments guests remember.', image:'horeca-interior-design.jpg', lessons:[
      {id:'atmosphere',title:'Designing atmosphere',duration:'14 min',intro:'Atmosphere is not decoration. It is the cumulative effect of hundreds of choices, made legible to a guest through a single evening.',body:'Light changes the pace of a room. Sound affects conversation. Tableware changes how a dish feels in the hand. The most compelling spaces bring these elements into alignment with the promise of the concept.',ideas:['Design for a sequence of moments, not a static photograph.','Service choreography is part of spatial design.','A sensory detail should reinforce the concept, not distract from it.'],case:'Himkok, Oslo',challenge:'Map three scenes in a venue you know: arrival, the peak moment and farewell. Identify one design choice in each.'}]},
    {id:'neuro', number:'03', title:'Neurogastronomy', description:'Understand how perception, psychology and environment influence food and beverage experiences.', image:'horeca-neurogastronomy-serve.jpg', lessons:[
      {id:'perception',title:'The senses at the table',duration:'16 min',intro:'Flavour is experienced through more than taste. Context, expectation and the other senses all participate in what a guest perceives.',body:'Gastrophysics examines how physical and psychological factors shape eating and drinking. A useful hospitality application is to treat the setting as part of the offer: the soundscape, vessel, lighting and story may all influence how an experience is interpreted.',ideas:['Perception is constructed from multiple sensory cues.','The remembered peak and ending can shape an entire visit.','Sensory design should be tested, not assumed.'],case:'A multisensory World Class serve',challenge:'Propose one sensory detail that could make a signature dish more memorable. Explain the intended effect.'}]},
    {id:'concepts', number:'04', title:'Restaurant & Bar Concepts', description:'Build a clear point of view through positioning, storytelling, atmosphere and business logic.', image:'horeca-craft-bar.jpg', lessons:[
      {id:'point-of-view',title:'A concept with a point of view',duration:'13 min',intro:'A concept becomes useful when it helps a team make choices. It should be more than a moodboard or a list of references.',body:'A compelling venue connects audience, occasion, offer, space and economics. Benchmarks can sharpen a point of view, but the work is deciding what to translate and what to leave behind.',ideas:['Define the guest and the occasion before the aesthetic.','A proposition should be clear enough to guide operations.','Distinctiveness and commercial logic can reinforce one another.'],case:'Bar Leone, Hong Kong',challenge:'Write a one-sentence proposition for a new venue, including audience, occasion and what makes it different.'}]},
    {id:'technology', number:'05', title:'Technology & Automation', description:'Consider where technology can improve operations and where the human touch matters most.', image:'horeca-tech-operations.jpg', lessons:[
      {id:'automation',title:'Automation without losing humanity',duration:'15 min',intro:'Technology should not simply make hospitality faster. It should make it better.',body:'The right tools reduce friction for guests and teams. Reservation systems, forecasting, inventory tools and kitchen displays can support consistency, but they do not replace judgement, generosity or a well-timed human response.',ideas:['Automate repetition; protect moments where human attention creates value.','Evaluate technology across guest experience and team experience.','A useful implementation begins with a clearly defined problem.'],case:'Technology in contemporary F&B operations',challenge:'Choose one repetitive task to automate in a venue. What will the team do with the time this creates?'}]},
    {id:'ai', number:'06', title:'AI in Hospitality', description:'Assess emerging AI workflows, their opportunities, limitations and human implications.', image:'horeca-ai-mixology-lab.jpg', lessons:[
      {id:'human-ai',title:'AI as a creative and operational tool',duration:'17 min',intro:'AI can help teams generate options and work with information. It cannot own the responsibility for what a hospitality business promises.',body:'From creative briefs to demand planning, AI tools can expand a team’s capacity. Their value depends on good inputs, critical review and thoughtful decisions about privacy, bias and work. Hospitality remains a human promise, even when some of its systems are automated.',ideas:['Use AI to widen exploration, then apply human judgement.','Be transparent about consequential automated decisions.','Do not mistake fluent output for reliable evidence.'],case:'An AI-assisted beverage brief',challenge:'Describe one hospitality workflow where AI could help, one risk to manage and the human decision that must remain.'}]},
    {id:'fnb', number:'07', title:'Food & Beverage Futures', description:'Look at new formats, ingredients, beverage culture and changing consumer behaviour.', image:'horeca-sustainable-terroir.jpg', lessons:[
      {id:'new-formats',title:'The next table',duration:'12 min',intro:'The future of food and beverage is shaped by culture, access and changing definitions of value.',body:'New formats emerge as operators respond to local identity, resource constraints and new occasions. A strong offer is rooted in a point of view about place and people, rather than novelty alone.',ideas:['Local context can be a source of distinction.','Value is shaped by relevance as much as price.','New formats need viable operating models.'],case:'Tuju, São Paulo',challenge:'Identify a food or beverage behaviour gaining momentum in your market. How might a venue respond with integrity?'}]},
    {id:'entrepreneurship', number:'08', title:'Entrepreneurship', description:'Move from a strong idea to an operationally grounded hospitality business.', image:'horeca-concept-pitch.jpg', lessons:[
      {id:'from-idea',title:'From idea to operating model',duration:'18 min',intro:'A hospitality business is a promise, delivered repeatedly by a team within real constraints.',body:'Concept development balances desirability, feasibility and viability. Define the guest and value proposition, then test the operating assumptions behind the experience: capacity, staffing, supply, pricing and the rhythm of demand.',ideas:['A clear proposition makes operating trade-offs visible.','Small tests can reduce uncertainty before major investment.','Culture and economics are both part of the concept.'],case:'From pop-up to permanent concept',challenge:'Name the riskiest assumption in your concept and design a low-cost way to test it.'}]},
    {id:'final', number:'09', title:'Final Challenge', description:'Bring your thinking together. Design the hospitality concept of tomorrow.', image:'horeca-concept-pitch.jpg', lessons:[
      {id:'final-brief',title:'Design the hospitality concept of tomorrow',duration:'20 min',intro:'Imagine you are building a hospitality concept for 2030. Make a case for the experience and the business that can deliver it.',body:'Your final concept should connect audience, experience, space, food and beverage, technology and a credible operating model. The strongest submissions demonstrate a clear point of view and explain how the details work together.',ideas:['Make the guest and occasion specific.','Show how design, service and technology reinforce one another.','Communicate the business logic behind the experience.'],case:'Your own concept, benchmarked against the industry',challenge:'Present your concept, target audience, guest journey, food and beverage offer, technology choices, business model and visual direction.'}]}
  ],
  cases:[
    {title:'Bar Leone',location:'Hong Kong',year:'2025',industry:'Bar culture · Guest experience',image:'horeca-craft-bar.jpg',context:'A contemporary neighbourhood bar framed around accessible, familiar drinks and a generous style of hospitality.',what:'Its proposition puts approachability and consistency at the centre of a globally visible bar concept.',why:'The case invites students to question whether innovation always needs to look complicated.',takeaway:'Clarity of intent can be more distinctive than visual or technical excess.'},
    {title:'Tuju',location:'São Paulo',year:'2026',industry:'Restaurant · Place & personalisation',image:'horeca-sustainable-terroir.jpg',context:'A restaurant concept that connects its menu to the rhythms of its environment and the character of its place.',what:'Seasonal themes and thoughtful guest details create a coherent narrative beyond the plate.',why:'It illustrates how local identity and considerate service can support an ambitious dining experience.',takeaway:'Personalisation is most meaningful when it grows from a real point of view.'},
    {title:'Himkok',location:'Oslo',year:'Case file',industry:'Bar · Design & circularity',image:'horeca-interior-sconces.jpg',context:'A bar whose approach brings together atmosphere, production and a distinctive sense of place.',what:'The case gives a lens on how spatial choices and in-house craft can reinforce a venue’s identity.',why:'Design is treated as an operating decision and part of the story, not a surface layer.',takeaway:'The best concepts make their values tangible in the way the venue works.'}
  ],
  updates:[{tag:'EDITION NOTE',title:'A living elective',date:'September 2026',text:'The 2026 edition is designed to evolve with hospitality — new cases and tools can be added without changing the learning journey.'}]
};
